const guests = {
  "Weronika Buż": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Weroniko",
    lastName: "Buż",
  },
  "Bożena Buż": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Bożeno",
    lastName: "Buż",
  },
  "Jacek Kocój": {
    gender: "male",
    partner: "Renata Kocój",
    partnerGender: "female",
    vocative: "Jacku",
    lastName: "Kocój",
    partnerVocative: "Renato",
    partnerLastName: "Kocój",
    sharedLastName: true,
    pluralLastName: "Kocój",
  },
  "Jakub Kocój": {
    gender: "male",
    partner: "Paulina Kocój",
    partnerGender: "female",
    vocative: "Jakubie",
    lastName: "Kocój",
    partnerVocative: "Paulino",
    partnerLastName: "Kocój",
    sharedLastName: true,
    pluralLastName: "Kocój",
  },
  "Paweł Kocój": {
    gender: "male",
    partner: "Justyna Kocój",
    partnerGender: "female",
    vocative: "Pawle",
    lastName: "Kocój",
    partnerVocative: "Justyno",
    partnerLastName: "Kocój",
    sharedLastName: true,
    pluralLastName: "Kocój",
  },
  "Monika Kocój": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Moniko",
    lastName: "Kocój",
  },
  "Barbara Wielgos": {
    gender: "female",
    partner: "Paweł Wielgos",
    partnerGender: "male",
    vocative: "Barbaro",
    lastName: "Wielgos",
    partnerVocative: "Pawle",
    partnerLastName: "Wielgos",
    sharedLastName: true,
    pluralLastName: "Wielgos",
  },
  "Elżbieta Pelc": {
    gender: "female",
    partner: "Leszek Pelc",
    partnerGender: "male",
    vocative: "Elżbieto",
    lastName: "Pelc",
    partnerVocative: "Leszku",
    partnerLastName: "Pelc",
    sharedLastName: true,
    pluralLastName: "Pelc",
  },
  "Zuzanna Pelc": {
    gender: "female",
    partner: "Adam Krupa",
    partnerGender: "male",
    vocative: "Zuzanno",
    lastName: "Pelc",
    partnerVocative: "Adamie",
    partnerLastName: "Krupa",
    sharedLastName: false,
  },
  "Milena Pelc": {
    gender: "female",
    partner: "Mateusz Pelc",
    partnerGender: "male",
    vocative: "Mileno",
    lastName: "Pelc",
    partnerVocative: "Mateuszu",
    partnerLastName: "Pelc",
    sharedLastName: true,
    pluralLastName: "Pelc",
  },
  "Alicja Machnicka": {
    gender: "female",
    partner: "Wiesław Machnicki",
    partnerGender: "male",
    vocative: "Alu",
    lastName: "Machnicka",
    partnerVocative: "Wiesławie",
    partnerLastName: "Machnicki",
    sharedLastName: true,
    pluralLastName: "Machniccy",
  },
  "Mateusz Machnicki": {
    gender: "male",
    partner: "Agnieszka Oczoś",
    partnerGender: "female",
    vocative: "Mateuszu",
    lastName: "Machnicki",
    partnerVocative: "Agnieszko",
    partnerLastName: "Oczoś",
    sharedLastName: false,
  },
  "Przemysław Kubicz": {
    gender: "male",
    partner: "",
    partnerGender: null,
    vocative: "Przemysławie",
    lastName: "Kubicz",
  },
  "Aleksander Nowak": {
    gender: "male",
    partner: "",
    partnerGender: null,
    vocative: "Aleksandrze",
    lastName: "Nowak",
  },
  "Wojtek Hałdys": {
    gender: "male",
    partner: "",
    partnerGender: null,
    vocative: "Wojtku",
    lastName: "Hałdys",
  },
  "Szymon Ruchała": {
    gender: "male",
    partner: "",
    partnerGender: null,
    vocative: "Szymonie",
    lastName: "Ruchała",
  },
  "Paweł Kolasa": {
    gender: "male",
    partner: "",
    partnerGender: null,
    vocative: "Pawle",
    lastName: "Kolasa",
  },
  "Jolanta Prokop": {
    gender: "female",
    partner: "Piotr Prokop",
    partnerGender: "male",
    vocative: "Jolanto",
    lastName: "Prokop",
    partnerVocative: "Piotrze",
    partnerLastName: "Prokop",
    sharedLastName: true,
    pluralLastName: "Prokop",
  },
  "Paulina Prokop": {
    gender: "female",
    partner: "Krystian Puc",
    partnerGender: "male",
    vocative: "Paulino",
    lastName: "Prokop",
    partnerVocative: "Krystianie",
    partnerLastName: "Puc",
    sharedLastName: false,
  },
  "Anna Prokop": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Anno",
    lastName: "Prokop",
  },
  "Elżbieta Bilska": {
    gender: "female",
    partner: "Stanisław Bilski",
    partnerGender: "male",
    vocative: "Elżbieto",
    lastName: "Bilska",
    partnerVocative: "Stanisławie",
    partnerLastName: "Bilski",
    sharedLastName: true,
    pluralLastName: "Bilscy",
  },
  "Beata Zubiak": {
    gender: "female",
    partner: "Łukasz Zubiak",
    partnerGender: "male",
    vocative: "Beato",
    lastName: "Zubiak",
    partnerVocative: "Łukaszu",
    partnerLastName: "Zubiak",
    sharedLastName: true,
    pluralLastName: "Zubiak",
  },
  "Monika Piekiełek": {
    gender: "female",
    partner: "Wojtek Piekiełek",
    partnerGender: "male",
    vocative: "Moniko",
    lastName: "Piekiełek",
    partnerVocative: "Wojtku",
    partnerLastName: "Piekiełek",
    sharedLastName: true,
    pluralLastName: "Piekiełek",
  },
  "Ewa Buż": {
    gender: "female",
    partner: "Krzysztof Buż",
    partnerGender: "male",
    vocative: "Ewo",
    lastName: "Buż",
    partnerVocative: "Krzysztofie",
    partnerLastName: "Buż",
    sharedLastName: true,
    pluralLastName: "Buż",
  },
  "Martyna Buż": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Martyno",
    lastName: "Buż",
  },
  "Zuzanna Bilska": {
    gender: "female",
    partner: "Tomasz Zawitkowski",
    partnerGender: "male",
    vocative: "Zuzanno",
    lastName: "Bilska",
    partnerVocative: "Tomaszu",
    partnerLastName: "Zawitkowski",
    sharedLastName: false,
  },
  "Julia Bilska": {
    gender: "female",
    partner: "Łukasz Ledwoń",
    partnerGender: "male",
    vocative: "Julio",
    lastName: "Bilska",
    partnerVocative: "Łukaszu",
    partnerLastName: "Ledwoń",
    sharedLastName: false,
  },
  "Tomasz Bilski": {
    gender: "male",
    partner: "Justyna Bilska",
    partnerGender: "female",
    vocative: "Tomaszu",
    lastName: "Bilski",
    partnerVocative: "Justyno",
    partnerLastName: "Bilska",
    sharedLastName: true,
    pluralLastName: "Bilscy",
  },
  "Renata Kulawska": {
    gender: "female",
    partner: "Marek Kulawski",
    partnerGender: "male",
    vocative: "Renato",
    lastName: "Kulawska",
    partnerVocative: "Marku",
    partnerLastName: "Kulawski",
    sharedLastName: true,
    pluralLastName: "Kulawscy",
  },
  "Kamila Kulawska": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Kamilo",
    lastName: "Kulawska",
  },
  "Wiktoria Halerz": {
    gender: "female",
    partner: "Jakub Warchoł",
    partnerGender: "male",
    vocative: "Wiktorio",
    lastName: "Halerz",
    partnerVocative: "Jakubie",
    partnerLastName: "Warchoł",
    sharedLastName: false,
  },
  "Julia Sarna": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Julio",
    lastName: "Sarna",
  },
  "Natalia Sarna": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Natalio",
    lastName: "Sarna",
  },
  "Alessia De Rosa": {
    gender: "female",
    partner: "Igor Barć",
    partnerGender: "male",
    vocative: "Alessio",
    lastName: "De Rosa",
    partnerVocative: "Igorze",
    partnerLastName: "Barć",
    sharedLastName: false,
  },
  "Klaudia Sękowska": {
    gender: "female",
    partner: "Sebastian Sękowski",
    partnerGender: "male",
    vocative: "Klaudiu",
    lastName: "Sękowska",
    partnerVocative: "Sebastianie",
    partnerLastName: "Sękowski",
    sharedLastName: true,
    pluralLastName: "Sękowscy",
  },
  "Kinga Dyło": {
    gender: "female",
    partner: "Piotr Dyło",
    partnerGender: "male",
    vocative: "Kingo",
    lastName: "Dyło",
    partnerVocative: "Piotrze",
    partnerLastName: "Dyło",
    sharedLastName: true,
    pluralLastName: "Dyło",
  },
  "Kacper Najdecki": {
    gender: "male",
    partner: "",
    partnerGender: null,
    vocative: "Kacprze",
    lastName: "Najdecki",
  },
  "Elżbieta Kowal": {
    gender: "female",
    partner: "Andrzej Kowal",
    partnerGender: "male",
    vocative: "Elżbieto",
    lastName: "Kowal",
    partnerVocative: "Andrzeju",
    partnerLastName: "Kowal",
    sharedLastName: true,
    pluralLastName: "Kowal",
  },
};

const guestsKlaudia = {
  "Jolanta Prokop": {
    gender: "female",
    partner: "Piotr Prokop",
    partnerGender: "male",
    vocative: "Jolanto",
    lastName: "Prokop",
    partnerVocative: "Piotrze",
    partnerLastName: "Prokop",
    sharedLastName: true,
    pluralLastName: "Prokop",
  },
  "Paulina Prokop": {
    gender: "female",
    partner: "Krystian Puc",
    partnerGender: "male",
    vocative: "Paulino",
    lastName: "Prokop",
    partnerVocative: "Krystianie",
    partnerLastName: "Puc",
    sharedLastName: false,
  },
  "Anna Prokop": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Anno",
    lastName: "Prokop",
  },
  "Elżbieta Bilska": {
    gender: "female",
    partner: "Stanisław Bilski",
    partnerGender: "male",
    vocative: "Elżbieto",
    lastName: "Bilska",
    partnerVocative: "Stanisławie",
    partnerLastName: "Bilski",
    sharedLastName: true,
    pluralLastName: "Bilscy",
  },
  "Beata Zubiak": {
    gender: "female",
    partner: "Łukasz Zubiak",
    partnerGender: "male",
    vocative: "Beato",
    lastName: "Zubiak",
    partnerVocative: "Łukaszu",
    partnerLastName: "Zubiak",
    sharedLastName: true,
    pluralLastName: "Zubiak",
  },
  "Monika Piekiełek": {
    gender: "female",
    partner: "Wojtek Piekiełek",
    partnerGender: "male",
    vocative: "Moniko",
    lastName: "Piekiełek",
    partnerVocative: "Wojtku",
    partnerLastName: "Piekiełek",
    sharedLastName: true,
    pluralLastName: "Piekiełek",
  },
  "Ewa Buż": {
    gender: "female",
    partner: "Krzysztof Buż",
    partnerGender: "male",
    vocative: "Ewo",
    lastName: "Buż",
    partnerVocative: "Krzysztofie",
    partnerLastName: "Buż",
    sharedLastName: true,
    pluralLastName: "Buż",
  },
  "Martyna Buż": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Martyno",
    lastName: "Buż",
  },
  "Zuzanna Bilska": {
    gender: "female",
    partner: "Tomasz Zawitkowski",
    partnerGender: "male",
    vocative: "Zuzanno",
    lastName: "Bilska",
    partnerVocative: "Tomaszu",
    partnerLastName: "Zawitkowski",
    sharedLastName: false,
  },
  "Julia Bilska": {
    gender: "female",
    partner: "Łukasz Ledwoń",
    partnerGender: "male",
    vocative: "Julio",
    lastName: "Bilska",
    partnerVocative: "Łukaszu",
    partnerLastName: "Ledwoń",
    sharedLastName: false,
  },
  "Tomasz Bilski": {
    gender: "male",
    partner: "Justyna Bilska",
    partnerGender: "female",
    vocative: "Tomaszu",
    lastName: "Bilski",
    partnerVocative: "Justyno",
    partnerLastName: "Bilska",
    sharedLastName: true,
    pluralLastName: "Bilscy",
  },
  "Renata Kulawska": {
    gender: "female",
    partner: "Marek Kulawski",
    partnerGender: "male",
    vocative: "Renato",
    lastName: "Kulawska",
    partnerVocative: "Marku",
    partnerLastName: "Kulawski",
    sharedLastName: true,
    pluralLastName: "Kulawscy",
  },
  "Kamila Kulawska": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Kamilo",
    lastName: "Kulawska",
  },
  "Wiktoria Halerz": {
    gender: "female",
    partner: "Jakub Warchoł",
    partnerGender: "male",
    vocative: "Wiktorio",
    lastName: "Halerz",
    partnerVocative: "Jakubie",
    partnerLastName: "Warchoł",
    sharedLastName: false,
  },
  "Julia Sarna": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Julio",
    lastName: "Sarna",
  },
  "Natalia Sarna": {
    gender: "female",
    partner: "",
    partnerGender: null,
    vocative: "Natalio",
    lastName: "Sarna",
  },
  "Alessia De Rossa": {
    gender: "female",
    partner: "Igor Barć",
    partnerGender: "male",
    vocative: "Alessio",
    lastName: "De Rossa",
    partnerVocative: "Igorze",
    partnerLastName: "Barć",
    sharedLastName: false,
  },
  "Klaudia Sękowska": {
    gender: "female",
    partner: "Sebastian Sękowski",
    partnerGender: "male",
    vocative: "Klaudiu",
    lastName: "Sękowska",
    partnerVocative: "Sebastianie",
    partnerLastName: "Sękowski",
    sharedLastName: true,
    pluralLastName: "Sękowscy",
  },
  "Kinga Dyło": {
    gender: "female",
    partner: "Piotr Dyło",
    partnerGender: "male",
    vocative: "Kingo",
    lastName: "Dyło",
    partnerVocative: "Piotrze",
    partnerLastName: "Dyło",
    sharedLastName: true,
    pluralLastName: "Dyło",
  },
  "Kacper Najdecki": {
    gender: "male",
    partner: "",
    partnerGender: null,
    vocative: "Kacprze",
    lastName: "Najdecki",
  },
  "Elżbieta Kowal": {
    gender: "female",
    partner: "Andrzej Kowal",
    partnerGender: "male",
    vocative: "Elżbieto",
    lastName: "Kowal",
    partnerVocative: "Andrzeju",
    partnerLastName: "Kowal",
    sharedLastName: true,
    pluralLastName: "Kowal",
  },
};
